name: cognition_package_demo_app
description: A demo application for the Cognition Package
publish_to: none
version: 1.2.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter

  cognition_package:
    path: ../../cognition_package
  research_package:
    path: ../../research.package/

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
