name: cognition_package
description: A Flutter framework for cognitive testing. Contains 14 pre-defined cognitive tests and an API for creating your own.
version: 1.3.1
homepage: https://github.com/cph-cachet/cognition_package

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.0.0
  json_annotation: ^4.7.0
  audioplayers: ^1.0.1
  research_package: ^1.1.0
  reorderables: ^0.5.0

dev_dependencies:
  flutter_lints: any
  test: any
  build_runner: any 
  json_serializable: any

flutter:
  uses-material-design: true
  assets:
    #mp files for letter A tapping test
    - packages/cognition_package/assets/sounds/A.mp3
    - packages/cognition_package/assets/sounds/B.mp3
    - packages/cognition_package/assets/sounds/C.mp3
    - packages/cognition_package/assets/sounds/D.mp3
    - packages/cognition_package/assets/sounds/E.mp3
    - packages/cognition_package/assets/sounds/F.mp3
    - packages/cognition_package/assets/sounds/G.mp3
    - packages/cognition_package/assets/sounds/H.mp3
    - packages/cognition_package/assets/sounds/I.mp3
    - packages/cognition_package/assets/sounds/J.mp3
    - packages/cognition_package/assets/sounds/K.mp3
    - packages/cognition_package/assets/sounds/L.mp3
    - packages/cognition_package/assets/sounds/M.mp3
    - packages/cognition_package/assets/sounds/N.mp3
    - packages/cognition_package/assets/sounds/O.mp3
    - packages/cognition_package/assets/sounds/P.mp3
    - packages/cognition_package/assets/sounds/Q.mp3
    - packages/cognition_package/assets/sounds/R.mp3
    - packages/cognition_package/assets/sounds/S.mp3
    - packages/cognition_package/assets/sounds/T.mp3
    - packages/cognition_package/assets/sounds/U.mp3
    - packages/cognition_package/assets/sounds/V.mp3
    - packages/cognition_package/assets/sounds/W.mp3
    - packages/cognition_package/assets/sounds/X.mp3
    - packages/cognition_package/assets/sounds/Y.mp3
    - packages/cognition_package/assets/sounds/Z.mp3
    - packages/cognition_package/assets/sounds/FACE.mp3
    - packages/cognition_package/assets/sounds/VELVET.mp3
    - packages/cognition_package/assets/sounds/CHURCH.mp3
    - packages/cognition_package/assets/sounds/DAISY.mp3
    - packages/cognition_package/assets/sounds/RED.mp3

    - packages/cognition_package/assets/sounds/ICECREAM.mp3
    - packages/cognition_package/assets/sounds/DESK.mp3
    - packages/cognition_package/assets/sounds/BANANA.mp3
    - packages/cognition_package/assets/sounds/VIOLIN.mp3
    - packages/cognition_package/assets/sounds/GREEN.mp3

    # Test image assets for PAL
    - packages/cognition_package/assets/images/nothing.png
    - packages/cognition_package/assets/images/hidden.png
    - packages/cognition_package/assets/images/shape1.png
    - packages/cognition_package/assets/images/shape2.png
    - packages/cognition_package/assets/images/shape3.png
    - packages/cognition_package/assets/images/shape4.png
    - packages/cognition_package/assets/images/shape5.png
    - packages/cognition_package/assets/images/hourglass_blue.png
    - packages/cognition_package/assets/images/hourglass_red.png
    - packages/cognition_package/assets/images/hourglass_yellow.png
    - packages/cognition_package/assets/images/top_blue.png
    - packages/cognition_package/assets/images/top_red.png
    - packages/cognition_package/assets/images/top_yellow.png
    - packages/cognition_package/assets/images/arrow_blue.png
    - packages/cognition_package/assets/images/arrow_red.png
    - packages/cognition_package/assets/images/arrow_yellow.png

    - packages/cognition_package/assets/images/hourglass_1.png
    - packages/cognition_package/assets/images/hourglass_2.png
    - packages/cognition_package/assets/images/hourglass_3.png
    - packages/cognition_package/assets/images/hourglass_4.png
    - packages/cognition_package/assets/images/hourglass_1.png
    - packages/cognition_package/assets/images/hourglass_5.png

    - packages/cognition_package/assets/images/arrow_1.png
    - packages/cognition_package/assets/images/arrow_2.png
    - packages/cognition_package/assets/images/arrow_3.png
    - packages/cognition_package/assets/images/arrow_4.png
    - packages/cognition_package/assets/images/arrow_1.png
    - packages/cognition_package/assets/images/arrow_5.png

    - packages/cognition_package/assets/images/boomerang_1.png
    - packages/cognition_package/assets/images/boomerang_2.png
    - packages/cognition_package/assets/images/boomerang_3.png
    - packages/cognition_package/assets/images/boomerang_4.png
    - packages/cognition_package/assets/images/boomerang_1.png
    - packages/cognition_package/assets/images/boomerang_5.png

    - packages/cognition_package/assets/images/bean_1.png
    - packages/cognition_package/assets/images/bean_2.png
    - packages/cognition_package/assets/images/bean_3.png
    - packages/cognition_package/assets/images/bean_4.png
    - packages/cognition_package/assets/images/bean_1.png
    - packages/cognition_package/assets/images/bean_5.png

    - packages/cognition_package/assets/images/bowl_1.png
    - packages/cognition_package/assets/images/bowl_2.png
    - packages/cognition_package/assets/images/bowl_3.png
    - packages/cognition_package/assets/images/bowl_4.png
    - packages/cognition_package/assets/images/bowl_1.png
    - packages/cognition_package/assets/images/bowl_5.png

    # Test intro images
    - packages/cognition_package/assets/images/PALintro.png
    - packages/cognition_package/assets/images/Corsiintro.png
    - packages/cognition_package/assets/images/Reactionintro.png
    - packages/cognition_package/assets/images/RVIPintro.png
    - packages/cognition_package/assets/images/Stroopintro.png
    - packages/cognition_package/assets/images/Tappingintro.png
    - packages/cognition_package/assets/images/trailtype-a.png
    - packages/cognition_package/assets/images/trailtype-b.png
    - packages/cognition_package/assets/images/Letterintro.png

    - packages/cognition_package/assets/images/trailmaking_a.png
    - packages/cognition_package/assets/images/trailmaking_b.png
    - packages/cognition_package/assets/images/visual_tracking.png
    - packages/cognition_package/assets/images/picture_sequence.png
    - packages/cognition_package/assets/images/wordlist_recall.png
    - packages/cognition_package/assets/images/letter_tapping.png
    - packages/cognition_package/assets/images/flanker.png
    - packages/cognition_package/assets/images/shape_recall.png
    - packages/cognition_package/assets/images/delayed_recall.png
